#!/usr/bin/env python3
"""Single source of truth for STM32/K210/OpenMV/CarLink protocol constants.

This file intentionally owns all cross-language protocol values. Run
``python3 tools/generate_protocol_contract.py --check`` before release to verify
that generated C/Python headers are synchronized with this source.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

PROTOCOL_VERSION_MAJOR = 2
PROTOCOL_VERSION_MINOR = 3
PROTOCOL_VERSION_BYTE = ((PROTOCOL_VERSION_MAJOR & 0x0F) << 4) | (PROTOCOL_VERSION_MINOR & 0x0F)

MAGIC0 = 0xAA
MAGIC1 = 0xFF
TAIL = 0xCC

# Wire format sizes. STM32 ISR RX buffers add one local byte at index 0 that
# stores the number of received wire bytes; this byte is not transmitted.
OPENMV_WIRE_FRAME_SIZE = 12
K210_WIRE_FRAME_SIZE = 12
CARLINK_WIRE_FRAME_SIZE = 11
OPENMV_RX_BUFFER_SIZE = OPENMV_WIRE_FRAME_SIZE + 1
K210_RX_BUFFER_SIZE = K210_WIRE_FRAME_SIZE + 1

K210_CONFIDENCE_MIN = 55
K210_CLASS_THRESHOLDS = {
    "1": 70, "2": 70, "3": 70, "4": 70,
    "5": 55, "6": 70, "7": 70, "8": 70,
}

CARLINK_MSG_SET_DETECT = 1
CARLINK_MSG_LEAVE = 2
CARLINK_MSG_GO = 3
CARLINK_MSG_HEARTBEAT = 4
CARLINK_MSG_ACK = 0x7F


def checksum8(values) -> int:
    return sum(int(v) & 0xFF for v in values) & 0xFF


def pack_k210_wire(class_mask: int, confidence: int, x: int, y: int, seq: int) -> bytes:
    """Return the exact 12-byte K210 UART wire frame."""
    payload = [
        MAGIC0, MAGIC1, PROTOCOL_VERSION_BYTE,
        class_mask & 0xFF,
        confidence & 0xFF,
        (x >> 8) & 0xFF, x & 0xFF,
        (y >> 8) & 0xFF, y & 0xFF,
        seq & 0xFF,
    ]
    return bytes([*payload, checksum8(payload), TAIL])


def pack_k210_rxbuf(class_mask: int, confidence: int, x: int, y: int, seq: int) -> bytes:
    """Return STM32 local RX buffer layout: length byte + K210 wire frame."""
    return bytes([K210_WIRE_FRAME_SIZE, *pack_k210_wire(class_mask, confidence, x, y, seq)])


def pack_openmv_wire(center_x: int, east_y: int, west_y: int, black_num: int) -> bytes:
    """Return the exact 12-byte OpenMV UART wire frame."""
    payload = [
        MAGIC0, MAGIC1, PROTOCOL_VERSION_BYTE,
        (center_x >> 8) & 0xFF, center_x & 0xFF,
        (east_y >> 8) & 0xFF, east_y & 0xFF,
        (west_y >> 8) & 0xFF, west_y & 0xFF,
        black_num & 0xFF,
    ]
    return bytes([*payload, checksum8(payload), TAIL])


def pack_openmv_rxbuf(center_x: int, east_y: int, west_y: int, black_num: int) -> bytes:
    """Return STM32 local RX buffer layout: length byte + OpenMV wire frame."""
    return bytes([OPENMV_WIRE_FRAME_SIZE, *pack_openmv_wire(center_x, east_y, west_y, black_num)])


def pack_carlink(msg_type: int, value: int, seq: int, sender_role: int) -> bytes:
    payload = [
        MAGIC0, MAGIC1,
        msg_type & 0xFF,
        value & 0xFF,
        seq & 0xFF,
        sender_role & 0xFF,
        PROTOCOL_VERSION_MAJOR,
        PROTOCOL_VERSION_MINOR,
    ]
    return bytes([*payload, checksum8(payload), 0x00, TAIL])


def render_c_generated_header() -> str:
    return f"""#ifndef PROTOCOL_CONTRACT_GENERATED_H__
#define PROTOCOL_CONTRACT_GENERATED_H__

/* Generated by tools/generate_protocol_contract.py from tools/protocol_contract.py. */
#define CAR_PROTOCOL_VERSION_MAJOR  {PROTOCOL_VERSION_MAJOR}u
#define CAR_PROTOCOL_VERSION_MINOR  {PROTOCOL_VERSION_MINOR}u
#define CAR_PROTOCOL_VERSION_BYTE   0x{PROTOCOL_VERSION_BYTE:02X}u
#define CAR_PROTOCOL_MAGIC0         0x{MAGIC0:02X}u
#define CAR_PROTOCOL_MAGIC1         0x{MAGIC1:02X}u
#define CAR_PROTOCOL_TAIL           0x{TAIL:02X}u
#define CAR_K210_FRAME_SIZE         {K210_WIRE_FRAME_SIZE}u
#define CAR_OPENMV_FRAME_SIZE       {OPENMV_WIRE_FRAME_SIZE}u
#define CAR_LINK_FRAME_SIZE         {CARLINK_WIRE_FRAME_SIZE}u
#define CAR_K210_CONFIDENCE_MIN     {K210_CONFIDENCE_MIN}u

#endif /* PROTOCOL_CONTRACT_GENERATED_H__ */
"""


def render_device_python(module_name: str) -> str:
    thresholds = "{" + ", ".join(f"{k!r}: {v}" for k, v in K210_CLASS_THRESHOLDS.items()) + "}"
    return f"""# Generated by ../tools/generate_protocol_contract.py from tools/protocol_contract.py.
FRAME_MAGIC0 = 0x{MAGIC0:02X}
FRAME_MAGIC1 = 0x{MAGIC1:02X}
FRAME_TAIL = 0x{TAIL:02X}
PROTOCOL_VERSION_MAJOR = {PROTOCOL_VERSION_MAJOR}
PROTOCOL_VERSION_MINOR = {PROTOCOL_VERSION_MINOR}
PROTOCOL_VERSION_BYTE = 0x{PROTOCOL_VERSION_BYTE:02X}
K210_WIRE_FRAME_SIZE = {K210_WIRE_FRAME_SIZE}
OPENMV_WIRE_FRAME_SIZE = {OPENMV_WIRE_FRAME_SIZE}
K210_CONFIDENCE_MIN = {K210_CONFIDENCE_MIN}
K210_CLASS_THRESHOLDS = {thresholds}
"""


def render_host_header() -> str:
    return f"""#ifndef PROTOCOL_CONTRACT_HOST_H__
#define PROTOCOL_CONTRACT_HOST_H__

/* Generated by tools/generate_protocol_contract.py from tools/protocol_contract.py. */
#define HOST_PROTOCOL_VERSION_MAJOR {PROTOCOL_VERSION_MAJOR}u
#define HOST_PROTOCOL_VERSION_MINOR {PROTOCOL_VERSION_MINOR}u
#define HOST_PROTOCOL_VERSION_BYTE  0x{PROTOCOL_VERSION_BYTE:02X}u
#define HOST_MAGIC0 0x{MAGIC0:02X}u
#define HOST_MAGIC1 0x{MAGIC1:02X}u
#define HOST_TAIL 0x{TAIL:02X}u
#define HOST_K210_FRAME_SIZE {K210_WIRE_FRAME_SIZE}u
#define HOST_OPENMV_FRAME_SIZE {OPENMV_WIRE_FRAME_SIZE}u
#define HOST_CARLINK_FRAME_SIZE {CARLINK_WIRE_FRAME_SIZE}u
#define HOST_CARLINK_MSG_SET_DETECT {CARLINK_MSG_SET_DETECT}u
#define HOST_CARLINK_MSG_LEAVE {CARLINK_MSG_LEAVE}u
#define HOST_CARLINK_MSG_GO {CARLINK_MSG_GO}u
#define HOST_CARLINK_MSG_HEARTBEAT {CARLINK_MSG_HEARTBEAT}u
#define HOST_CARLINK_MSG_ACK 0x{CARLINK_MSG_ACK:02X}u

static inline unsigned char host_checksum8(const unsigned char *frame, unsigned int count)
{{
    unsigned int i;
    unsigned int sum = 0u;
    for(i = 0u; i < count; ++i)
    {{
        sum += frame[i];
    }}
    return (unsigned char)(sum & 0xFFu);
}}

#endif /* PROTOCOL_CONTRACT_HOST_H__ */
"""
