#ifndef PROTOCOL_CONTRACT_GENERATED_H__
#define PROTOCOL_CONTRACT_GENERATED_H__

/* Generated by tools/generate_protocol_contract.py from tools/protocol_contract.py. */
#define CAR_PROTOCOL_VERSION_MAJOR  2u
#define CAR_PROTOCOL_VERSION_MINOR  3u
#define CAR_PROTOCOL_VERSION_BYTE   0x23u
#define CAR_PROTOCOL_MAGIC0         0xAAu
#define CAR_PROTOCOL_MAGIC1         0xFFu
#define CAR_PROTOCOL_TAIL           0xCCu
#define CAR_K210_FRAME_SIZE         12u
#define CAR_OPENMV_FRAME_SIZE       12u
#define CAR_LINK_FRAME_SIZE         11u
#define CAR_K210_CONFIDENCE_MIN     55u

#endif /* PROTOCOL_CONTRACT_GENERATED_H__ */
