#ifndef CAR_STRATEGY_SHARED_H__
#define CAR_STRATEGY_SHARED_H__

#include CAR_STRATEGY_TASK1_HEADER
#include CAR_STRATEGY_TASK2_HEADER
#include CAR_STRATEGY_TASK3_HEADER
#include CAR_STRATEGY_COMMON_HEADER

#define CAR_STRATEGY_NAME CAR_STRATEGY_NAME_LITERAL

#endif /* CAR_STRATEGY_SHARED_H__ */
