#ifndef PROTOCOL_CONTRACT_HOST_H__
#define PROTOCOL_CONTRACT_HOST_H__

/* Generated by tools/generate_protocol_contract.py from tools/protocol_contract.py. */
#define HOST_PROTOCOL_VERSION_MAJOR 2u
#define HOST_PROTOCOL_VERSION_MINOR 3u
#define HOST_PROTOCOL_VERSION_BYTE  0x23u
#define HOST_MAGIC0 0xAAu
#define HOST_MAGIC1 0xFFu
#define HOST_TAIL 0xCCu
#define HOST_K210_FRAME_SIZE 12u
#define HOST_OPENMV_FRAME_SIZE 12u
#define HOST_CARLINK_FRAME_SIZE 11u
#define HOST_CARLINK_MSG_SET_DETECT 1u
#define HOST_CARLINK_MSG_LEAVE 2u
#define HOST_CARLINK_MSG_GO 3u
#define HOST_CARLINK_MSG_HEARTBEAT 4u
#define HOST_CARLINK_MSG_ACK 0x7Fu

static inline unsigned char host_checksum8(const unsigned char *frame, unsigned int count)
{
    unsigned int i;
    unsigned int sum = 0u;
    for(i = 0u; i < count; ++i)
    {
        sum += frame[i];
    }
    return (unsigned char)(sum & 0xFFu);
}

#endif /* PROTOCOL_CONTRACT_HOST_H__ */
