[platformio]
default_envs = car1

description = 2021-F-drug_car STM32F407 PlatformIO workspace

[env]
platform = platformio/ststm32
framework = spl
board = black_f407zg
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
  -DSTM32F40_41xxx
  -DUSE_STDPERIPH_DRIVER

[env:car1]
build_src_filter =
  +<car1/USER/main.c>
  +<car1/USER/stm32f4xx_it.c>
  +<car1/SYSTEM/*.c>
  +<car1/SYSTEM/CHE/*.c>
  +<car1/SYSTEM/ANO_V7/*.c>
  +<car1/SYSTEM/delay/*.c>
  +<car1/SYSTEM/oled/*.c>
  +<car1/SYSTEM/pid/*.c>
  +<car1/SYSTEM/sys/*.c>
  +<car1/MOTOR_shuanghuan/*.c>
lib_ldf_mode = chain+
build_flags =
  ${env.build_flags}
  -Isrc/COMMON/CHE
  -Isrc/COMMON/STRATEGY
  -Isrc/car1/USER
  -Isrc/car1/SYSTEM
  -Isrc/car1/SYSTEM/CHE
  -Isrc/car1/SYSTEM/PLATFORM
  -Isrc/car1/SYSTEM/STRATEGY/common
  -Isrc/car1/SYSTEM/STRATEGY/car1
  -Isrc/car1/SYSTEM/ANO_V7
  -Isrc/car1/SYSTEM/delay
  -Isrc/car1/SYSTEM/oled
  -Isrc/car1/SYSTEM/pid
  -Isrc/car1/SYSTEM/sys
  -Isrc/car1/MOTOR_shuanghuan

[env:car2]
build_src_filter =
  +<car2/USER/main.c>
  +<car2/USER/stm32f4xx_it.c>
  +<car2/SYSTEM/*.c>
  +<car2/SYSTEM/CHE/*.c>
  +<car2/SYSTEM/ANO_V7/*.c>
  +<car2/SYSTEM/delay/*.c>
  +<car2/SYSTEM/oled/*.c>
  +<car2/SYSTEM/pid/*.c>
  +<car2/SYSTEM/sys/*.c>
  +<car2/MOTOR_shuanghuan/*.c>
lib_ldf_mode = chain+
build_flags =
  ${env.build_flags}
  -Isrc/COMMON/CHE
  -Isrc/COMMON/STRATEGY
  -Isrc/car2/USER
  -Isrc/car2/SYSTEM
  -Isrc/car2/SYSTEM/CHE
  -Isrc/car2/SYSTEM/PLATFORM
  -Isrc/car2/SYSTEM/STRATEGY/common
  -Isrc/car2/SYSTEM/STRATEGY/car2
  -Isrc/car2/SYSTEM/ANO_V7
  -Isrc/car2/SYSTEM/delay
  -Isrc/car2/SYSTEM/oled
  -Isrc/car2/SYSTEM/pid
  -Isrc/car2/SYSTEM/sys
  -Isrc/car2/MOTOR_shuanghuan


[env:native]
platform = native
test_build_src = no
build_flags =
  -Iinclude
  -Itest/host
  -Isrc/COMMON/CHE
  -Isrc/COMMON/STRATEGY
