#ifndef HOST_PLATFORM_H__
#define HOST_PLATFORM_H__

#include <stdint.h>
#include "../../include/protocol_contract_host.h"

typedef uint8_t u8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;

#define CAR_PROTOCOL_VERSION_MAJOR HOST_PROTOCOL_VERSION_MAJOR
#define CAR_PROTOCOL_VERSION_MINOR HOST_PROTOCOL_VERSION_MINOR
#define CAR_PROTOCOL_VERSION_BYTE HOST_PROTOCOL_VERSION_BYTE
#define CAR_PROTOCOL_MAGIC0 HOST_MAGIC0
#define CAR_PROTOCOL_MAGIC1 HOST_MAGIC1
#define CAR_PROTOCOL_TAIL HOST_TAIL
#define CAR_K210_FRAME_SIZE HOST_K210_FRAME_SIZE
#define CAR_OPENMV_FRAME_SIZE HOST_OPENMV_FRAME_SIZE
#define CAR_LINK_FRAME_SIZE HOST_CARLINK_FRAME_SIZE
#define CAR_K210_MAGIC0 HOST_MAGIC0
#define CAR_K210_MAGIC1 HOST_MAGIC1
#define CAR_K210_TAIL HOST_TAIL
#define CAR_OPENMV_MAGIC0 HOST_MAGIC0
#define CAR_OPENMV_MAGIC1 HOST_MAGIC1
#define CAR_OPENMV_TAIL HOST_TAIL
#define CAR_LINK_MAGIC0 HOST_MAGIC0
#define CAR_LINK_MAGIC1 HOST_MAGIC1
#define CAR_LINK_TAIL HOST_TAIL
#define CAR_K210_CLASS_COUNT 8u
#define CAR_K210_DECISION_MIN_COUNT 2
#define CAR_PROTOCOL_REJECT_VERSION_MISMATCH 1u
#define CAR_PROTOCOL_COMPAT_V1 1u
#define CAR_VISUAL_PROTOCOL_COMPAT_V1 1u
#define CAR_LINK_COMPAT_TASK_FIELD 1u
#define CAR_LINK_MSG_SET_DETECT HOST_CARLINK_MSG_SET_DETECT
#define CAR_LINK_MSG_LEAVE HOST_CARLINK_MSG_LEAVE
#define CAR_LINK_MSG_GO HOST_CARLINK_MSG_GO
#define CAR_LINK_MSG_HEARTBEAT HOST_CARLINK_MSG_HEARTBEAT
#define CAR_LINK_MSG_ACK HOST_CARLINK_MSG_ACK

extern long long int system_time;
extern u8 find_val1;
extern u8 find_val2;
extern u8 find_val3;
extern u8 find_val4;
extern int val1_cnt;
extern int val2_cnt;
extern int val3_cnt;
extern int val4_cnt;

#endif /* HOST_PLATFORM_H__ */
